In [1]:
import os
import json
import pandas as pd

# Go two directories up
os.chdir("..")
os.chdir("..")

In [3]:

# File paths
file_paths = [
    "datasets/cwe20cfa/cwe20cfa_train.jsonl",
    "datasets/cwe20cfa/cwe20cfa_valid.jsonl",
    "datasets/cwe20cfa/cwe20cfa_test.jsonl"
]

# Accumulator for all records
all_records = []

for path in file_paths:
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:  # skip empty lines
                try:
                    all_records.append(json.loads(line))
                except json.JSONDecodeError as e:
                    print(f"Skipping malformed line in {path}: {e}")

# Convert to DataFrame
original_cwe20cfa_complete = pd.DataFrame(all_records)

# Preview
original_cwe20cfa_complete.head()

,idx,project,commit_id,project_url,commit_url,commit_message,target,func,func_hash,file_name,file_hash,cwe,cve,cve_desc,nvd_url
0,0,openssl,ca989269a2876bae79393bd54c3e72d49975fc75,https://github.com/openssl/openssl,https://git.openssl.org/gitweb/?p=openssl.git;...,Use version in SSL_METHOD not SSL structure.\n...,1,long ssl_get_algorithm2(SSL *s)\n {\n ...,255087747659226932756944884868284698117,None,NaN,[CWE-310],CVE-2013-6449,The ssl_get_algorithm2 function in ssl/s3_lib....,https://nvd.nist.gov/vuln/detail/CVE-2013-6449
1,1,savannah,190cef6eed37d0e73a73c1e205eb31d45ab60a3c,https://git.savannah.gnu.org/gitweb/?p=gnutls,https://git.savannah.gnu.org/gitweb/?p=gnutls....,None,1,gnutls_session_get_data (gnutls_session_t sess...,266005388725654386397960628110885023158,None,NaN,[CWE-119],CVE-2011-4128,Buffer overflow in the gnutls_session_get_data...,https://nvd.nist.gov/vuln/detail/CVE-2011-4128
2,2,savannah,e82ef4545e9e98cbcb032f55d7c750b81e3a0450,https://git.savannah.gnu.org/gitweb/?p=gnutls,https://git.savannah.gnu.org/gitweb/?p=gnutls....,None,1,gnutls_session_get_data (gnutls_session_t sess...,162619476999663411812822607346255778028,None,NaN,[CWE-119],CVE-2011-4128,Buffer overflow in the gnutls_session_get_data...,https://nvd.nist.gov/vuln/detail/CVE-2011-4128
3,3,savannah,075d7556964f5a871a73c22ac4b69f5361295099,https://git.savannah.gnu.org/gitweb/?p=gnutls,https://git.savannah.gnu.org/cgit/wget.git/com...,None,1,"getftp (struct url *u, wgint passed_expected_b...",114753069609161113628525870463495041364,None,NaN,[CWE-200],CVE-2015-7665,Tails before 1.7 includes the wget program but...,https://nvd.nist.gov/vuln/detail/CVE-2015-7665
4,5,ghostscript,83d4dae44c71816c084a635550acc1a51529b881,http://git.ghostscript.com/?p=mupdf,http://git.ghostscript.com/?p=mupdf.git;a=comm...,None,1,void fz_init_cached_color_converter(fz_context...,183139468890710880163111516517773812467,colorspace.c,6.862522e+36,[CWE-20],CVE-2018-1000040,"In MuPDF 1.12.0 and earlier, multiple use of u...",https://nvd.nist.gov/vuln/detail/CVE-2018-1000040

In [4]:
len(original_cwe20cfa_complete)

224533

In [14]:
original_cwe20cfa_complete['target'].value_counts()

target
0    218529
1      6004
Name: count, dtype: int64

In [8]:
original_cwe20cfa_cwe_20 = original_cwe20cfa_complete[original_cwe20cfa_complete['cwe'].apply(lambda cwe_list: 'CWE-20' in cwe_list)]
original_cwe20cfa_cwe_20

,idx,project,commit_id,project_url,commit_url,commit_message,target,func,func_hash,file_name,file_hash,cwe,cve,cve_desc,nvd_url
4,5,ghostscript,83d4dae44c71816c084a635550acc1a51529b881,http://git.ghostscript.com/?p=mupdf,http://git.ghostscript.com/?p=mupdf.git;a=comm...,None,1,void fz_init_cached_color_converter(fz_context...,183139468890710880163111516517773812467,colorspace.c,6.862522e+36,[CWE-20],CVE-2018-1000040,"In MuPDF 1.12.0 and earlier, multiple use of u...",https://nvd.nist.gov/vuln/detail/CVE-2018-1000040
8,9,ghostscript,b2e7d38e845c7d4922d05e6e41f3a2dc1bc1b14a,http://git.ghostscript.com/?p=mupdf,http://git.ghostscript.com/?p=mupdf.git;a=comm...,None,1,"pdf_show_image(fz_context *ctx, pdf_run_proce...",327424409628836476675717770567987598130,None,NaN,[CWE-20],CVE-2018-1000037,"In MuPDF 1.12.0 and earlier, multiple reachabl...",https://nvd.nist.gov/vuln/detail/CVE-2018-1000037
16,53,savannah,7a42b78be9a4108d98833069a88e6fddb9285008,https://git.savannah.gnu.org/gitweb/?p=gnutls,https://git.savannah.gnu.org/cgit/quagga.git/c...,None,1,"aspath_put (struct stream *s, struct aspath *a...",180268846652331292477605901092801668823,bgp_aspath.c,2.008558e+38,[CWE-20],CVE-2017-16227,The aspath_put function in bgpd/bgp_aspath.c i...,https://nvd.nist.gov/vuln/detail/CVE-2017-16227
22,65,poppler,61f79b8447c3ac8ab5a26e79e0c28053ffdccf75,https://github.com/freedesktop/poppler,https://cgit.freedesktop.org/poppler/poppler/c...,Allow only one %d in the filename\n\nFixes cra...,1,"bool extractPages (const char *srcFileName, co...",41887122719404523174993334902149265910,None,NaN,[CWE-20],CVE-2013-4474,Format string vulnerability in the extractPage...,https://nvd.nist.gov/vuln/detail/CVE-2013-4474
35,84,dbus,c3223ba6c401ba81df1305851312a47c485e6cd7,http://gitweb.freedesktop.org/?p=dbus/dbus,https://cgit.freedesktop.org/dbus/dbus/commit/...,_dbus_header_byteswap: change the first byte o...,1,"_dbus_header_byteswap (DBusHeader *header,\n ...",9228036298590962222843680821307727463,dbus-marshal-header.c,1.260657e+38,[CWE-20],CVE-2011-2200,The _dbus_header_byteswap function in dbus-mar...,https://nvd.nist.gov/vuln/detail/CVE-2011-2200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222738,503986,core,2c3f37672277b1f73f84722802aaa0ab1ab3e413,https://github.com/LibreOffice/core,https://github.com/dovecot/core/commit/2c3f376...,auth: Don't crash expanding %variables when us...,0,static const char *field_get_default(const cha...,2580830718591610323478151842461984595,None,NaN,[CWE-20],CVE-2016-8652,"The auth component in Dovecot before 2.2.27, w...",https://nvd.nist.gov/vuln/detail/CVE-2016-8652
222739,503987,core,2c3f37672277b1f73f84722802aaa0ab1ab3e413,https://github.com/LibreOffice/core,https://github.com/dovecot/core/commit/2c3f376...,auth: Don't crash expanding %variables when us...,0,auth_request_var_expand_func_passdb(const char...,25981339862751467132692830201694523136,None,NaN,[CWE-20],CVE-2016-8652,"The auth component in Dovecot before 2.2.27, w...",https://nvd.nist.gov/vuln/detail/CVE-2016-8652
222740,503988,core,2c3f37672277b1f73f84722802aaa0ab1ab3e413,https://github.com/LibreOffice/core,https://github.com/dovecot/core/commit/2c3f376...,auth: Don't crash expanding %variables when us...,0,"t_auth_request_var_expand(const char *str,\n\t...",188986629024205829482200731208666019202,None,NaN,[CWE-20],CVE-2016-8652,"The auth component in Dovecot before 2.2.27, w...",https://nvd.nist.gov/vuln/detail/CVE-2016-8652
222741,503989,core,2c3f37672277b1f73f84722802aaa0ab1ab3e413,https://github.com/LibreOffice/core,https://github.com/dovecot/core/commit/2c3f376...,auth: Don't crash expanding %variables when us...,0,auth_request_get_var_expand_table(const struct...,93327504864719046330773621577573232945,None,NaN,[CWE-20],CVE-2016-8652,"The auth component in Dovecot before 2.2.27, w...",https://nvd.nist.gov/vuln/detail/CVE-2016-8652
222742,503990,core,2c3f37672277b1f73f84722802aaa0ab1ab3e413,https://github.com/LibreOffice/core,https://github.com/dovecot/core/commit/2c3f376...,auth: Don't crash expanding %variables when us...,0,auth_request_var_expand_func_userdb(const char...,11416809754444017609562040300435902188,None,NaN,[CWE-20],CVE-2016-8652,"The auth component in Dovecot before 2.2.27, w...",https://nvd.nist.gov/vuln/detail/CVE-2016-8652

In [13]:
original_cwe20cfa_cwe_20['target'].value_counts()

target
0    14473
1      471
Name: count, dtype: int64

## Augmented CWE-20 cwe20cfa

In [9]:
import pandas as pd

cwe20cfa_cwe_20_aug = pd.read_pickle('datasets/cwe20cfa/cwe20cfa_CWE-20_augmented_input_balanced.pkl')
cwe20cfa_cwe_20_aug

,adv,code_embedding_mapping,cpg,cwe,func,id,input,line_to_tokens_map,nodes,nodes_by_line_map,target,tokens
0,False,"{'MethodReturn@d': ('void RET', [-0.1495839, 0...",{'functions': [{'function': 'fz_init_cached_co...,CWE-20,void fz_init_cached_color_converter(fz_context...,4,"[(x, [tensor([ 1.5000e+01, -1.4958e-01, 1.899...","{0: ['void', 'FUN1', '(', 'fz_context', '*', '...",{'MethodReturn@d': Node id: MethodReturn@d...,"{'1': ['void RET', 'fz_context *ctx', 'fz_cont...",1,"[void, FUN1, (, fz_context, *, VAR1, ,, fz_col..."
1,True,"{'MethodReturn@15': ('void RET', [-0.24205795,...",{'functions': [{'function': 'fz_init_cached_co...,CWE-20,void fz_init_cached_color_converter(fz_context...,4,"[(x, [tensor([15.0000, -0.2421, 0.1372, -0.20...","{0: ['void', 'FUN1', '(', 'fz_context', '*', '...",{'MethodReturn@15': Node id: MethodReturn@...,"{'1': ['void RET', 'fz_context *ctx', 'fz_cont...",0,"[void, FUN1, (, fz_context, *, VAR1,, fz_color..."
2,False,"{'MethodReturn@f': ('int RET', [-0.15379667, -...","{'functions': [{'function': 'pdf_show_image', ...",CWE-20,"pdf_show_image(fz_context *ctx, pdf_run_proce...",8,"[(x, [tensor([ 1.5000e+01, -1.5380e-01, -2.612...","{0: ['FUN1', '(', 'fz_context', '*', 'VAR1', '...",{'MethodReturn@f': Node id: MethodReturn@f...,"{'1': ['int RET', 'fz_context *ctx', 'fz_conte...",1,"[FUN1, (, fz_context, *, VAR1, ,, pdf_run_proc..."
3,True,"{'MethodReturn@d': ('void RET', [-0.24239674, ...","{'functions': [{'function': 'pdf_show_image', ...",CWE-20,#include <stdio.h>\n#include <stdlib.h>\n\nvoi...,8,"[(x, [tensor([15.0000, -0.2424, 0.1377, -0.20...","{0: ['#VAR1', '<', 'VAR2', '.', 'VAR3', '>'], ...",{'MethodReturn@d': Node id: MethodReturn@d...,"{'4': ['void RET', 'fz_context *ctx', 'fz_cont...",0,"[#VAR1, <, VAR2, ., VAR3, >, #VAR1, <, VAR2, ...."
4,False,"{'MethodReturn@11': ('int RET', [-0.1527507, 0...","{'functions': [{'function': 'aspath_put', 'id'...",CWE-20,"aspath_put (struct stream *s, struct aspath *a...",16,"[(x, [tensor([ 1.5000e+01, -1.5275e-01, 1.971...","{0: ['FUN1', '(', 'struct', 'stream', '*', 'VA...",{'MethodReturn@11': Node id: MethodReturn@...,"{'1': ['int RET', 'struct stream *s', 'struct ...",1,"[FUN1, (, struct, stream, *, VAR1, ,, struct, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
27551,True,"{'MethodReturn@10': ('static int RET', [-0.244...",{'functions': [{'function': 'cborElemNameToJso...,CWE-20,static int cborElemNameToJson (OSCTXT* pCborCt...,175753,"[(x, [tensor([ 1.5000e+01, -2.4499e-01, 1.212...","{0: ['static', 'int', 'FUN1', '(', 'VAR1', '*'...",{'MethodReturn@10': Node id: MethodReturn@...,"{'1': ['static int RET', 'OSCTXT * OSCTXT* pCb...",1,"[static, int, FUN1, (, VAR1, *, VAR2,, VAR1, *..."
27552,False,"{'MethodReturn@14': ('int RET', [-0.15187076, ...","{'functions': [{'function': 'main', 'id': 'nod...",CWE-20,"int main (int argc, char** argv)\r\n{\r\n OS...",175754,"[(x, [tensor([ 1.5000e+01, -1.5187e-01, -9.502...","{0: ['int', 'main', '(', 'int', 'argc', ',', '...",{'MethodReturn@14': Node id: MethodReturn@...,"{'1': ['int RET', 'int argc', 'int argc', 'cha...",0,"[int, main, (, int, argc, ,, char, **, argv, )..."
27553,True,"{'MethodReturn@12': ('int RET', [-0.24573934, ...","{'functions': [{'function': 'main', 'id': 'nod...",CWE-20,#include <stdio.h>\n#include <string.h>\n#incl...,175754,"[(x, [tensor([ 1.5000e+01, -2.4574e-01, 1.323...","{0: ['#VAR1', '<', 'VAR2', '.', 'VAR3', '>'], ...",{'MethodReturn@12': Node id: MethodReturn@...,"{'5': ['int RET', 'int argc', 'int argc', 'cha...",1,"[#VAR1, <, VAR2, ., VAR3, >, #VAR1, <, VAR2, ...."
27554,False,"{'MethodReturn@16': ('static int RET', [-0.134...","{'functions': [{'function': 'cbor2json', 'id':...",CWE-20,"static int cbor2json (OSCTXT* pCborCtxt, OSCTX...",175755,"[(x, [tensor([ 1.5000e+01, -1.3459e-01, 1.692...","{0: ['static', 'int', 'FUN1', '(', 'VAR1', '*'...",{'MethodReturn@16': Node id: MethodReturn@...,"{'1': ['static int RET', 'OSCTXT * OSCTXT* pCb...",0,"[static, int, FUN1, (, VAR1, *, VAR2, ,, VAR1,..."
27555,True,"{'MethodReturn@1b': ('static int RET', [-0.246...","{'functions': [{'function': 'cbor2json', 'id':...",CWE-20,"static int cbor2json (OSCTXT* pCborCtxt, OSCTX...",175755,"[(x, [tensor([ 1.5000e+01, -2.4694e-01, 1.204...","{0: ['static', 'int', 'FUN1', '(', 'VAR1', '*'...",{'MethodReturn@1b': Node id: MethodReturn@...,"{'1': ['static int RET', 'OSCTXT * OSCTXT* pCb...",1,"[static, int, FUN1, (, VAR1, *, VAR2,, VAR1, *..."

In [12]:
cwe20cfa_cwe_20_aug['target'].value_counts()

target
1    13778
0    13778
Name: count, dtype: int64

In [20]:
print("Benign distribution (Original / Counterexamples)")
print(cwe20cfa_cwe_20_aug[cwe20cfa_cwe_20_aug['target'] == 0]['adv'].value_counts())

print("\Vulnerable distribution (Original / Counterexamples)")
print(cwe20cfa_cwe_20_aug[cwe20cfa_cwe_20_aug['target'] == 1]['adv'].value_counts())

Benign distribution (Original / Counterexamples)
adv
False    13349
True       429
Name: count, dtype: int64
\Vulnerable distribution (Original / Counterexamples)
adv
True     13349
False      429
Name: count, dtype: int64

In [ ]:
cwe20cfa_cwe_20_aug.loc[10397]

adv                                                                    True
code_embedding_mapping    {'MethodReturn@d': ('void RET', [-0.15767303, ...
cpg                       {'functions': [{'function': 'RenderFrameDevToo...
cwe                                                                  CWE-20
func                      #include <cstring> // For strlen\n\nvoid Rende...
id                                                                    59427
input                     [(x, [tensor([ 1.5000e+01, -1.5767e-01, -2.205...
line_to_tokens_map        {0: ['#VAR1', '<', 'VAR2', '>'], 2: ['void', '...
nodes                     {'MethodReturn@d':
			Node id: MethodReturn@d...
nodes_by_line_map         {'3': ['void RET', 'char * char* userInput', '...
target                                                                    1
tokens                    [#VAR1, <, VAR2, >, #VAR1, <, VAR2, >, void, V...
Name: 10397, dtype: object

: