# Pearson R

In [5]:
import pandas as pd

scmetrics = pd.read_csv("benchmarks\scmetrics_test.csv", index_col=0)
scmetrics

,benchmark_split,P-C,P-V,P-B,P-R,wga_k2,wga_k3,wga_k4,wga_k5,wga_k6,wga_k7,n_purity,intra_var_ben,intra_var_vul,inter_dist
0,100_0,4.4993,0.0000,95.4282,0.0726,0.017127,0.009569,0.007299,0.006745,0.005814,0.006682,0.707039,0.011029,0.010273,0.000607
1,90_10,74.0929,1.3788,23.8752,0.6531,0.730887,0.715556,0.705202,0.712644,0.590909,0.595238,0.907039,0.011203,0.010346,0.000732
2,80_20,91.0740,5.4427,3.2656,0.2177,0.911504,0.882845,0.875676,0.851240,0.844444,0.820513,0.952612,0.010959,0.010460,0.000266
3,70_30,94.6299,4.8621,0.3628,0.1451,0.905605,0.874477,0.875676,0.859504,0.844444,0.820513,0.961901,0.011089,0.009954,0.000104
4,60_40,93.6865,6.3135,0.0000,0.0000,0.905605,0.874477,0.870270,0.851240,0.844444,0.820513,0.966909,0.011337,0.010297,0.000101
5,50_50,95.7910,0.4354,0.0000,3.7736,0.899083,0.866667,0.855491,0.808696,0.795455,0.809524,0.944340,0.010608,0.010303,0.001599
6,40_60,94.1219,1.0160,4.4993,0.3628,0.847095,0.808889,0.809249,0.773913,0.795455,0.806723,0.965602,0.011223,0.010358,0.000172
7,30_70,87.5181,8.1277,3.8462,0.5080,0.877676,0.840000,0.826590,0.773913,0.772727,0.785714,0.940965,0.011013,0.010098,0.000383
8,20_80,70.9724,27.7213,1.0160,0.2903,0.882006,0.862222,0.849711,0.817391,0.818182,0.833333,0.929390,0.011442,0.010360,0.000277
9,10_90,77.9390,20.5370,0.6531,0.8708,0.858407,0.835017,0.815152,0.826471,0.814935,0.809859,0.909833,0.011034,0.010459,0.000075
10,0_100,41.5094,57.4020,0.6531,0.4354,0.539823,0.498316,0.503030,0.496552,0.475410,0.474227,0.856459,0.011215,0.010072,0.000994

Compute the Pearson r between WGA_2 and Neighbor Purity

In [11]:
import numpy as np

wga2   = scmetrics["wga_k2"]
purity = scmetrics["n_purity"]

scmetrics[["wga_k2", "n_purity"]]

      wga_k2  n_purity
0   0.017127  0.707039
1   0.730887  0.907039
2   0.911504  0.952612
3   0.905605  0.961901
4   0.905605  0.966909
5   0.899083  0.944340
6   0.847095  0.965602
7   0.877676  0.940965
8   0.882006  0.929390
9   0.858407  0.909833
10  0.539823  0.856459

In [19]:
# Remove outlier 100/0
pearson = np.corrcoef(wga2[1:], purity[1:])[0,1]
print(f"r: {pearson:.2f}")

r: 0.88